package exceptions;

public class ExDemo1 {
	public static void main(String[] args) {
		
		try{
			int a  = 20;
			int b = 0;
			double d = a/b;
			System.out.println("No Exception...");
		}catch(ArithmeticException e){
			System.out.println(e);
		}

		System.out.println("Normal Flow Resumed...");
	}
}
