package exceptions.testthrows;

public class Main {

}
