package exceptions;

public class ExDemo1 {
	public static void main(String[] args) {
		int a  = 20;
		int b = 0;
		try{
			double d = a/b;
		}catch(ArithmeticException e){
			System.out.println(e);
		}
		
		
		System.out.println("No Exception...");
		System.out.println("Normal Flow Resumed...");
	}
}
