package exceptions.testthrows;

public class B {
	public void f2(){
		new C().f3();
	}
}
